# Generated by Django 5.2 on 2025-06-01 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion_corta', models.CharField(max_length=200, null=True)),
                ('descripcion_larga', models.TextField()),
                ('ubicacion', models.TextField()),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('hora_inicio', models.TimeField(default=0)),
                ('hora_fin', models.TimeField(default=0)),
                ('iframe_mapa', models.TextField(blank=True, null=True)),
                ('imagen_principal', models.ImageField(null=True, upload_to='eventos')),
                ('imagen_secundaria', models.ImageField(null=True, upload_to='eventos')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.eventos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'evento')},
            },
        ),
    ]
