# Generated by Django 5.2 on 2025-05-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('Empresario', 'Empresario'), ('tourist', 'Turista')], default='tourist', max_length=10),
        ),
    ]
