# Generated by Django 5.2 on 2025-05-11 17:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hoteles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio_noche', models.FloatField(default=0)),
                ('descripcion', models.TextField(max_length=300)),
                ('estrellas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('ubicacion', models.TextField()),
                ('resenas', models.IntegerField(default=0)),
                ('habitaciones', models.IntegerField(default=0)),
                ('habitaciones_libres', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_register_hotels', 'Registrar hoteles')],
            },
        ),
        migrations.CreateModel(
            name='ImagenesH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='hoteles')),
                ('fk_hoteles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteles.hoteles')),
            ],
        ),
    ]
