# Generated by Django 5.2 on 2025-05-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteles',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
