# Generated by Django 5.2 on 2025-05-29 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0003_alter_hoteles_descripcion_alter_hoteles_estrellas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteles',
            name='resenas',
        ),
    ]
